In [1]:
import os
from pathlib import Path

import sys
sys.path.append('./coeqwalpackage')

import numpy as np
import pandas as pd
import datetime as dt
import re

from coeqwalpackage.metrics import (
    read_in_df, add_water_year_column, create_subset_list, create_subset_unit,
    compute_percent_of_capacity, compute_annual_means_list,
    compute_cv_scenario_variable, freq_and_prob_storage_ge_flood
)
from coeqwalpackage.tier import generate_tier_assignment_matrix
import cqwlutils as cu
from cqwlutils import (
    find_calsim_model_root, find_repo_root, get_relative_folder,
    strip_leveldv_from_columns, strip_level_from_columns
)

## Configuration

In [2]:
# Configuration parameters
CtrlFile = 'CalSim3DataExtractionInitFile_v4.xlsx'
CtrlTab = 'Init'

hist_percentiles = [0.2, 0.333, 0.5]  # percentiles for historical record
tier_thresholds = (0.9, 0.67, 0.3)  # tier assignment thresholds

cdec_calsim_vars = {
    "SHA": "S_SHSTA",
    "CLE": "S_TRNTY",
    "ORO": "S_OROVL",
    "FOL": "S_FOLSM",
    "NML": "S_MELON",
    "MIL": "S_MLRTN",
    "LUS": "S_SLUIS_SWP",
    "SLF": "S_SLUIS_CVP"
}  # mapping between cdec and calsim var names

cdec_file = "CDEC_Station_Key.csv"  # cdec key file name
metadata_file = "reservoir_metadata_table.csv"  # reservoir metadata output file name
file_prefix = "20250506_MonthlyResData_CDEC-"  # CDEC data file prefix

variables_storage = ["S_SHSTA_", "S_OROVL_", "S_FOLSM_", "S_TRNTY_", "S_SLUIS_CVP_", "S_SLUIS_SWP_", "S_MLRTN_", "S_MELON_"]
variables_floodpool = ["S_SHSTALEVEL5DV", "S_OROVLLEVEL5DV", "S_FOLSMLEVEL5DV", "S_TRNTYLEVEL4DV", "S_SLUIS_CVPLEVEL4DV", "S_SLUIS_SWPLEVEL4DV", "S_MLRTNLEVEL4", "S_MELONLEVEL4DV"]
variables_capacity = ["S_SHSTALEVEL6DV", "S_OROVLLEVEL6DV", "S_FOLSMLEVEL6DV", "S_TRNTYLEVEL5DV", "S_SLUIS_CVPLEVEL5DV", "S_SLUIS_SWPLEVEL5DV", "S_MLRTNLEVEL5DV", "S_MELONLEVEL5DV"]
units = "TAF"

# Output file names
Apr_Storage_Volume_file = "April_Reservoir_Storage_Volume.csv"
Sep_Storage_Volume_file = "September_Reservoir_Storage_Volume.csv"
Apr_Storage_Volume_CV_file = "April_Reservoir_Storage_Volume_CV.csv"
Sep_Storage_Volume_CV_file = "September_Reservoir_Storage_Volume_CV.csv"
Apr_Storage_Percent_file = "April_Reservoir_Storage_Percent.csv"
Sep_Storage_Percent_file = "September_Reservoir_Storage_Percent.csv"
Apr_Storage_Percent_CV_file = "April_Reservoir_Storage_Percent_CV.csv"
Sep_Storage_Percent_CV_file = "September_Reservoir_Storage_Percent_CV.csv"
Spill_Frequency_file = "Reservoir_Spill_Frequency.csv"
Spill_Probability_file = "Reservoir_Spill_Probability.csv"
all_metrics_filename = "storage_all_metrics.csv"

## Init

In [3]:
ScenarioListFile, ScenarioListTab, ScenarioListPath, DVDssNamesOutPath, SVDssNamesOutPath, ScenarioIndicesOutPath, DssDirsOutPath, VarListPath, VarListFile, VarListTab, VarOutPath, DataOutPath, ConvertDataOutPath, ExtractionSubPath, DemandDeliverySubPath, ModelSubPath, GroupDataDirPath, ScenarioDir, DVDssMin, DVDssMax, SVDssMin, SVDssMax, NameMin, NameMax, DirMin, DirMax, IndexMin, IndexMax, StartMin, StartMax, EndMin, EndMax, VarMin, VarMax, DemandFilePath, DemandFileName, DemandFileTab, DemMin, DemMax, InflowOutSubPath, InflowFilePath, InflowFileName, InflowFileTab, InflowMin, InflowMax = cu.read_init_file(CtrlFile, CtrlTab)

df, dss_names = read_in_df(ConvertDataOutPath, DVDssNamesOutPath)

var_df = add_water_year_column(df)
df_flat = df.copy()
df_flat.columns = ['_'.join(map(str, col)) if isinstance(col, tuple) else col for col in df_flat.columns]

In [4]:
repo_root = find_repo_root()
output_dir = repo_root / "CalSim3_Model_Runs" / "Scenarios" / "Performance_Metrics"
data_output_dir = output_dir / "Metrics" / "Reservoir_Storage"
data_output_dir.mkdir(parents=True, exist_ok=True)

Apr_Storage_Volume_path = data_output_dir / Apr_Storage_Volume_file
Sep_Storage_Volume_path = data_output_dir / Sep_Storage_Volume_file
Apr_Storage_Volume_CV_path = data_output_dir / Apr_Storage_Volume_CV_file
Sep_Storage_Volume_CV_path = data_output_dir / Sep_Storage_Volume_CV_file
Apr_Storage_Percent_path = data_output_dir / Apr_Storage_Percent_file
Sep_Storage_Percent_path = data_output_dir / Sep_Storage_Percent_file
Apr_Storage_Percent_CV_path = data_output_dir / Apr_Storage_Percent_CV_file
Sep_Storage_Percent_CV_path = data_output_dir / Sep_Storage_Percent_CV_file
Spill_Frequency_path = data_output_dir / Spill_Frequency_file
Spill_Probability_path = data_output_dir / Spill_Probability_file

## CDEC <-> CalSim table

In [5]:
base_model_dir = find_calsim_model_root()

hist_full_subdir = os.path.join(base_model_dir, "Scenarios", "CDEC_Historical_Monthly_Storage")
known_tail = os.path.join("CalSim3_Model_Runs", "Scenarios", "CDEC_Historical_Monthly_Storage")

hist_subdir = get_relative_folder(hist_full_subdir, known_tail)
print("hist_subdir: " + hist_subdir)

key_file = os.path.join(hist_subdir, cdec_file)
cdec_df = pd.read_csv(key_file)
cdec_df.columns = cdec_df.columns.str.strip()

cdec_df["CalSim_Variable"] = cdec_df["CDEC_Key"].map(cdec_calsim_vars)
cdec_df = cdec_df.dropna(subset=["CalSim_Variable"])

cdec_df["filename"] = file_prefix + cdec_df["CDEC_Key"] + ".csv"
cdec_df["file_path"] = cdec_df["filename"].apply(lambda f: os.path.join(hist_subdir, f))

final_table = cdec_df[["ReservoirName", "CDEC_Key", "CalSim_Variable", "filename", "file_path"]]
print(final_table)

if not os.path.exists(hist_subdir):
    print("Warning: directory " + hist_subdir + " does not exist and will be created")
    os.makedirs(hist_subdir)

output_path = os.path.join(hist_subdir, metadata_file)
final_table.to_csv(output_path, index=False)
print(f"\n Metadata table saved to: {output_path}")

hist_subdir: ..\..\CalSim3_Model_Runs\Scenarios\CDEC_Historical_Monthly_Storage
        ReservoirName CDEC_Key CalSim_Variable  \
0              Shasta      SHA         S_SHSTA
1             Trinity      CLE         S_TRNTY
2            Oroville      ORO         S_OROVL
3              Folsom      FOL         S_FOLSM
4         New Melones      NML         S_MELON
5           Millerton      MIL         S_MLRTN
6  San Luis - Federal      SLF     S_SLUIS_CVP
7    San Luis - State      LUS     S_SLUIS_SWP

                               filename  \
0  20250506_MonthlyResData_CDEC-SHA.csv
1  20250506_MonthlyResData_CDEC-CLE.csv
2  20250506_MonthlyResData_CDEC-ORO.csv
3  20250506_MonthlyResData_CDEC-FOL.csv
4  20250506_MonthlyResData_CDEC-NML.csv
5  20250506_MonthlyResData_CDEC-MIL.csv
6  20250506_MonthlyResData_CDEC-SLF.csv
7  20250506_MonthlyResData_CDEC-LUS.csv

                                           file_path
0  ..\..\CalSim3_Model_Runs\Scenarios\CDEC_Histor...
1  ..\..\CalSim3_Model_Runs\Scenarios\CDEC_Histor...
2  ..\..\CalSim3_Model_Runs\Scenarios\CDEC_Histor...
3  ..\..\CalSim3_Model_Runs\Scenarios\CDEC_Histor...
4  ..\..\CalSim3_Model_Runs\Scenarios\CDEC_Histor...
5  ..\..\CalSim3_Model_Runs\Scenarios\CDEC_Histor...
6  ..\..\CalSim3_Model_Runs\Scenarios\CDEC_Histor...
7  ..\..\CalSim3_Model_Runs\Scenarios\CDEC_Histor...

 Metadata table saved to: ..\..\CalSim3_Model_Runs\Scenarios\CDEC_Historical_Monthly_Storage\reservoir_metadata_table.csv

## Compute tiers

In [6]:
tier_df, prob_df = generate_tier_assignment_matrix(
    df_flat, cdec_df,
    percentiles=hist_percentiles,
    tier_thresholds=tier_thresholds,
    saveprobs=True,
    verbose=False)

 Tier assignment CSV saved to:
C:\Dino\COEQWAL\COEQWAL_GIT\CalSim3_Model_Runs\Scenarios\Performance_Metrics\Tiered_Outcome_Measures\Reservoir_Storage\Tiers\tier_assignment.csv

 Level probabilities CSV saved to:
C:\Dino\COEQWAL\COEQWAL_GIT\CalSim3_Model_Runs\Scenarios\Performance_Metrics\Metrics\Reservoir_Storage\level_probabilities.csv

In [7]:
tier_df.head(5)

,S_SHSTA_Storage_Tier,S_TRNTY_Storage_Tier,S_OROVL_Storage_Tier,S_FOLSM_Storage_Tier,S_MELON_Storage_Tier,S_MLRTN_Storage_Tier,S_SLUIS_CVP_Storage_Tier,S_SLUIS_SWP_Storage_Tier
Scenario,,,,,,,,
s0001,2.0,3.0,2.0,3.0,2.0,3.0,3.0,3.0
s0002,2.0,3.0,3.0,3.0,2.0,3.0,3.0,3.0
s0003,3.0,3.0,3.0,3.0,2.0,2.0,3.0,3.0
s0004,3.0,3.0,3.0,3.0,2.0,2.0,3.0,3.0
s0005,3.0,3.0,3.0,3.0,2.0,3.0,3.0,3.0

In [8]:
prob_df.head(5)

,S_SHSTA_Storage_TopProb,S_SHSTA_Storage_MidProb,S_SHSTA_Storage_LowProb,S_SHSTA_Storage_BotProb,S_TRNTY_Storage_TopProb,S_TRNTY_Storage_MidProb,S_TRNTY_Storage_LowProb,S_TRNTY_Storage_BotProb,S_OROVL_Storage_TopProb,S_OROVL_Storage_MidProb,...,S_MLRTN_Storage_LowProb,S_MLRTN_Storage_BotProb,S_SLUIS_CVP_Storage_TopProb,S_SLUIS_CVP_Storage_MidProb,S_SLUIS_CVP_Storage_LowProb,S_SLUIS_CVP_Storage_BotProb,S_SLUIS_SWP_Storage_TopProb,S_SLUIS_SWP_Storage_MidProb,S_SLUIS_SWP_Storage_LowProb,S_SLUIS_SWP_Storage_BotProb
Scenario,,,,,,,,,,,,,,,,,,,,,
s0001,0.55,0.25,0.06,0.14,0.42,0.10,0.24,0.24,0.17,0.51,...,0.15,0.53,0.56,0.04,0.22,0.18,0.31,0.09,0.04,0.56
s0002,0.50,0.23,0.11,0.16,0.40,0.09,0.22,0.29,0.15,0.51,...,0.14,0.54,0.52,0.07,0.16,0.25,0.33,0.08,0.08,0.51
s0003,0.39,0.25,0.12,0.24,0.42,0.08,0.19,0.31,0.10,0.43,...,0.07,0.23,0.41,0.11,0.10,0.38,0.32,0.06,0.05,0.57
s0004,0.34,0.23,0.14,0.29,0.38,0.09,0.14,0.39,0.08,0.42,...,0.10,0.21,0.38,0.11,0.09,0.42,0.31,0.08,0.08,0.53
s0005,0.31,0.21,0.15,0.33,0.33,0.13,0.10,0.44,0.08,0.41,...,0.10,0.23,0.37,0.07,0.10,0.46,0.30,0.09,0.07,0.54

## Compute metrics

In [9]:
storage_df = create_subset_list(var_df, variables_storage)
storage_df.head(5)

A                 CALSIM                                            \
B          S_FOLSM_s0001 S_MELON_s0001 S_MLRTN_s0001 S_OROVL_s0001
C                STORAGE       STORAGE       STORAGE       STORAGE
D                   1MON          1MON          1MON          1MON
E                 L2020A        L2020A        L2020A        L2020A
F               PER-AVER      PER-AVER      PER-AVER      PER-AVER
Units                TAF           TAF           TAF           TAF
1921-10-31     592.00000     1400.5924     247.27315     2268.9397
1921-11-30     497.46445     1409.5559     259.80800     2198.0598
1921-12-31     508.00860     1432.6313     319.01993     2245.1772
1922-01-31     523.46387     1453.0829     386.45508     2241.3930
1922-02-28     567.00000     1540.3782     439.00000     2509.7190

A                                                                           \
B          S_SHSTA_s0001 S_SLUIS_CVP_s0001 S_SLUIS_SWP_s0001 S_TRNTY_s0001
C                STORAGE           STORAGE           STORAGE       STORAGE
D                   1MON              1MON              1MON          1MON
E                 L2020A            L2020A            L2020A        L2020A
F               PER-AVER          PER-AVER          PER-AVER      PER-AVER
Units                TAF               TAF               TAF           TAF
1921-10-31     3057.8250         202.58127         462.50110     1771.0225
1921-11-30     2908.5920         357.79940         364.16653     1734.6102
1921-12-31     3076.5317         567.35187         543.17050     1740.1699
1922-01-31     3204.3298         732.15686         683.54144     1739.6285
1922-02-28     3585.4524         936.83940         885.41895     1763.0382

A                                       ...                                  \
B          S_FOLSM_s0002 S_MELON_s0002  ... S_SLUIS_SWP_s0063 S_TRNTY_s0063
C                STORAGE       STORAGE  ...           STORAGE       STORAGE
D                   1MON          1MON  ...              1MON          1MON
E                 L2020A        L2020A  ...            L2020A        L2020A
F               PER-AVER      PER-AVER  ...          PER-AVER      PER-AVER
Units                TAF           TAF  ...               TAF           TAF
1921-10-31     591.41130     1424.3630  ...         462.50110     1763.9967
1921-11-30     495.81158     1433.3606  ...         333.22006     1722.1268
1921-12-31     529.82180     1458.4075  ...         278.66904     1731.3923
1922-01-31     567.00000     1486.7411  ...         419.33664     1748.9802
1922-02-28     567.00000     1610.4905  ...         701.36170     1813.2855

A                                                                   \
B          S_FOLSM_s0065 S_MELON_s0065 S_MLRTN_s0065 S_OROVL_s0065
C                STORAGE       STORAGE       STORAGE       STORAGE
D                   1MON          1MON          1MON          1MON
E                 L2020A        L2020A        L2020A        L2020A
F               PER-AVER      PER-AVER      PER-AVER      PER-AVER
Units                TAF           TAF           TAF           TAF
1921-10-31     524.89355     1420.1565     247.81735     2209.9666
1921-11-30     455.06726     1430.8540     257.99347     2148.5366
1921-12-31     489.54507     1457.1155     299.65450     2245.0520
1922-01-31     529.24790     1487.2096     374.97076     2266.7330
1922-02-28     567.00000     1602.2317     439.00000     2591.2288

A
B          S_SHSTA_s0065 S_SLUIS_CVP_s0065 S_SLUIS_SWP_s0065 S_TRNTY_s0065
C                STORAGE           STORAGE           STORAGE       STORAGE
D                   1MON              1MON              1MON          1MON
E                 L2020A            L2020A            L2020A        L2020A
F               PER-AVER          PER-AVER          PER-AVER      PER-AVER
Units                TAF               TAF               TAF           TAF
1921-10-31     2955.3410         140.65884         462.50110     1763.7498
1921-11-30     2816.4312         335.72080         345.00278     1720.7537
1921-12-31     2984.6220         564.85376         589.36440     1718.2435
1922-01-31     3069.7114         751.40344         777.58270     1721.0048
1922-02-28     3499.6343         972.00000        1067.00000     1750.9734

[5 rows x 360 columns]

In [10]:
flood_df = create_subset_list(var_df, variables_floodpool)
flood_df.head(5)

A                         CALSIM                                            \
B          S_FOLSMLEVEL5DV_s0001 S_MELONLEVEL4DV_s0001 S_MLRTNLEVEL4_s0001
C                  STORAGE-LEVEL         STORAGE-LEVEL       STORAGE-LEVEL
D                           1MON                  1MON                1MON
E                         L2020A                L2020A              L2020A
F                       PER-AVER              PER-AVER            PER-AVER
Units                        TAF                   TAF                 TAF
1921-10-31                 712.0                1970.0               439.0
1921-11-30                 567.0                1970.0               439.0
1921-12-31                 567.0                1970.0               439.0
1922-01-31                 567.0                1970.0               439.0
1922-02-28                 567.0                1970.0               439.0

A                                                       \
B          S_OROVLLEVEL5DV_s0001 S_SHSTALEVEL5DV_s0001
C                  STORAGE-LEVEL         STORAGE-LEVEL
D                           1MON                  1MON
E                         L2020A                L2020A
F                       PER-AVER              PER-AVER
Units                        TAF                   TAF
1921-10-31                3057.0              3250.000
1921-11-30                3057.0              3252.100
1921-12-31                2828.8              3359.160
1922-01-31                3000.0              3833.280
1922-02-28                2712.6              4139.735

A                                                               \
B          S_SLUIS_CVPLEVEL4DV_s0001 S_SLUIS_SWPLEVEL4DV_s0001
C                      STORAGE-LEVEL             STORAGE-LEVEL
D                               1MON                      1MON
E                             L2020A                    L2020A
F                           PER-AVER                  PER-AVER
Units                            TAF                       TAF
1921-10-31                     972.0                    1067.0
1921-11-30                     972.0                    1067.0
1921-12-31                     972.0                    1067.0
1922-01-31                     972.0                    1067.0
1922-02-28                     972.0                    1067.0

A                                                                             \
B          S_TRNTYLEVEL4DV_s0001 S_FOLSMLEVEL5DV_s0002 S_MELONLEVEL4DV_s0002
C                  STORAGE-LEVEL         STORAGE-LEVEL         STORAGE-LEVEL
D                           1MON                  1MON                  1MON
E                         L2020A                L2020A                L2020A
F                       PER-AVER              PER-AVER              PER-AVER
Units                        TAF                   TAF                   TAF
1921-10-31                1850.0                 712.0                1970.0
1921-11-30                1850.0                 567.0                1970.0
1921-12-31                1850.0                 567.0                1970.0
1922-01-31                1900.0                 567.0                1970.0
1922-02-28                2000.0                 567.0                1970.0

A           ...                                                  \
B           ... S_SLUIS_SWPLEVEL4DV_s0063 S_TRNTYLEVEL4DV_s0063
C           ...             STORAGE-LEVEL         STORAGE-LEVEL
D           ...                      1MON                  1MON
E           ...                    L2020A                L2020A
F           ...                  PER-AVER              PER-AVER
Units       ...                       TAF                   TAF
1921-10-31  ...                    1067.0                1850.0
1921-11-30  ...                    1067.0                1850.0
1921-12-31  ...                    1067.0                1850.0
1922-01-31  ...                    1067.0                1900.0
1922-02-28  ...                    1067.0                2000.0

A                                                                           \
B          S_FOLSMLEVEL5DV_s0065 S_MELONLEVEL4DV_s0065 S_MLRTNLEVEL4_s0065
C                  STORAGE-LEVEL         STORAGE-LEVEL       STORAGE-LEVEL
D                           1MON                  1MON                1MON
E                         L2020A                L2020A              L2020A
F                       PER-AVER              PER-AVER            PER-AVER
Units                        TAF                   TAF                 TAF
1921-10-31                 712.0                1970.0               439.0
1921-11-30                 567.0                1970.0               439.0
1921-12-31                 567.0                1970.0               439.0
1922-01-31                 567.0                1970.0               439.0
1922-02-28                 567.0                1970.0               439.0

A                                                       \
B          S_OROVLLEVEL5DV_s0065 S_SHSTALEVEL5DV_s0065
C                  STORAGE-LEVEL         STORAGE-LEVEL
D                           1MON                  1MON
E                         L2020A                L2020A
F                       PER-AVER              PER-AVER
Units                        TAF                   TAF
1921-10-31             3050.9800              3250.000
1921-11-30             3050.9800              3252.100
1921-12-31             2706.3733              3359.160
1922-01-31             3041.1680              3833.280
1922-02-28             2675.3800              4119.134

A                                                               \
B          S_SLUIS_CVPLEVEL4DV_s0065 S_SLUIS_SWPLEVEL4DV_s0065
C                      STORAGE-LEVEL             STORAGE-LEVEL
D                               1MON                      1MON
E                             L2020A                    L2020A
F                           PER-AVER                  PER-AVER
Units                            TAF                       TAF
1921-10-31                     972.0                    1067.0
1921-11-30                     972.0                    1067.0
1921-12-31                     972.0                    1067.0
1922-01-31                     972.0                    1067.0
1922-02-28                     972.0                    1067.0

A
B          S_TRNTYLEVEL4DV_s0065
C                  STORAGE-LEVEL
D                           1MON
E                         L2020A
F                       PER-AVER
Units                        TAF
1921-10-31                1850.0
1921-11-30                1850.0
1921-12-31                1850.0
1922-01-31                1900.0
1922-02-28                2000.0

[5 rows x 355 columns]

In [11]:
capacity_df = create_subset_list(var_df, variables_capacity)
capacity_df.head(5)

A                         CALSIM                            \
B          S_SHSTALEVEL6DV_s0001 S_SLUIS_CVPLEVEL5DV_s0001
C                  STORAGE-LEVEL             STORAGE-LEVEL
D                           1MON                      1MON
E                         L2020A                    L2020A
F                       PER-AVER                  PER-AVER
Units                        TAF                       TAF
1921-10-31                4552.0                     972.0
1921-11-30                4552.0                     972.0
1921-12-31                4552.0                     972.0
1922-01-31                4552.0                     972.0
1922-02-28                4552.0                     972.0

A                                                           \
B          S_SLUIS_SWPLEVEL5DV_s0001 S_TRNTYLEVEL5DV_s0001
C                      STORAGE-LEVEL         STORAGE-LEVEL
D                               1MON                  1MON
E                             L2020A                L2020A
F                           PER-AVER              PER-AVER
Units                            TAF                   TAF
1921-10-31                    1067.0               2447.65
1921-11-30                    1067.0               2447.65
1921-12-31                    1067.0               2447.65
1922-01-31                    1067.0               2447.65
1922-02-28                    1067.0               2447.65

A                     MANUAL-ADD                                               \
B          S_FOLSMLEVEL6DV_s0001 S_MLRTNLEVEL5DV_s0001 S_OROVLLEVEL6DV _s0001
C                   STORAGE-ZONE          STORAGE-ZONE           STORAGE-ZONE
D                           1MON                  1MON                   1MON
E                         L2020A                L2020A                 L2020A
F                        PER-CUM               PER-CUM                PER-CUM
Units                        TAF                   TAF                    TAF
1921-10-31                   967                   524                 3424.8
1921-11-30                   967                   524                 3424.8
1921-12-31                   967                   524                 3424.8
1922-01-31                   967                   524                 3424.8
1922-02-28                   967                   524                 3424.8

A                                                CALSIM  \
B          S_MELONLEVEL5DV _s0001 S_SHSTALEVEL6DV_s0002
C                    STORAGE-ZONE         STORAGE-LEVEL
D                            1MON                  1MON
E                          L2020A                L2020A
F                         PER-CUM              PER-AVER
Units                         TAF                   TAF
1921-10-31                   2420                4552.0
1921-11-30                   2420                4552.0
1921-12-31                   2420                4552.0
1922-01-31                   2420                4552.0
1922-02-28                   2420                4552.0

A                                     ...             MANUAL-ADD  \
B          S_SLUIS_CVPLEVEL5DV_s0002  ... S_OROVLLEVEL6DV _s0063
C                      STORAGE-LEVEL  ...           STORAGE-ZONE
D                               1MON  ...                   1MON
E                             L2020A  ...                 L2020A
F                           PER-AVER  ...                PER-CUM
Units                            TAF  ...                    TAF
1921-10-31                     972.0  ...                 3424.8
1921-11-30                     972.0  ...                 3424.8
1921-12-31                     972.0  ...                 3424.8
1922-01-31                     972.0  ...                 3424.8
1922-02-28                     972.0  ...                 3424.8

A                                                CALSIM  \
B          S_MELONLEVEL5DV _s0063 S_SHSTALEVEL6DV_s0065
C                    STORAGE-ZONE         STORAGE-LEVEL
D                            1MON                  1MON
E                          L2020A                L2020A
F                         PER-CUM              PER-AVER
Units                         TAF                   TAF
1921-10-31                   2420                4552.0
1921-11-30                   2420                4552.0
1921-12-31                   2420                4552.0
1922-01-31                   2420                4552.0
1922-02-28                   2420                4552.0

A                                                               \
B          S_SLUIS_CVPLEVEL5DV_s0065 S_SLUIS_SWPLEVEL5DV_s0065
C                      STORAGE-LEVEL             STORAGE-LEVEL
D                               1MON                      1MON
E                             L2020A                    L2020A
F                           PER-AVER                  PER-AVER
Units                            TAF                       TAF
1921-10-31                     972.0                    1067.0
1921-11-30                     972.0                    1067.0
1921-12-31                     972.0                    1067.0
1922-01-31                     972.0                    1067.0
1922-02-28                     972.0                    1067.0

A                                           MANUAL-ADD                        \
B          S_TRNTYLEVEL5DV_s0065 S_FOLSMLEVEL6DV_s0065 S_MLRTNLEVEL5DV_s0065
C                  STORAGE-LEVEL          STORAGE-ZONE          STORAGE-ZONE
D                           1MON                  1MON                  1MON
E                         L2020A                L2020A                L2020A
F                       PER-AVER               PER-CUM               PER-CUM
Units                        TAF                   TAF                   TAF
1921-10-31               2447.65                   967                   524
1921-11-30               2447.65                   967                   524
1921-12-31               2447.65                   967                   524
1922-01-31               2447.65                   967                   524
1922-02-28               2447.65                   967                   524

A
B          S_OROVLLEVEL6DV _s0065 S_MELONLEVEL5DV _s0065
C                    STORAGE-ZONE           STORAGE-ZONE
D                            1MON                   1MON
E                          L2020A                 L2020A
F                         PER-CUM                PER-CUM
Units                         TAF                    TAF
1921-10-31                 3424.8                   2420
1921-11-30                 3424.8                   2420
1921-12-31                 3424.8                   2420
1922-01-31                 3424.8                   2420
1922-02-28                 3424.8                   2420

[5 rows x 360 columns]

In [12]:
Apr_Storage_df = compute_annual_means_list(storage_df, variables_storage, units=units, months=[4])
Apr_Storage_df.head(5)

C:\Dino\COEQWAL\COEQWAL_GIT\COEQWAL_V3\notebooks\coeqwalpackage\metrics.py:1006: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  ann_mean = subset_df.groupby("WaterYear").mean()
C:\Dino\COEQWAL\COEQWAL_GIT\COEQWAL_V3\notebooks\coeqwalpackage\metrics.py:1006: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  ann_mean = subset_df.groupby("WaterYear").mean()
C:\Dino\COEQWAL\COEQWAL_GIT\COEQWAL_V3\notebooks\coeqwalpackage\metrics.py:1006: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  ann_mean = subset_df.groupby("WaterYear").mean()
C:\Dino\COEQWAL\COEQWAL_GIT\COEQWAL_V3\notebooks\coeqwalpackage\metrics.py:1006: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  ann_mean = subset_df.groupby("WaterYear").mean()
C:\Dino\COEQWAL\COEQWAL_GIT\COEQWAL_V3\notebooks\coeqwalpackage\metrics.py:1006: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  ann_mean = subset_df.groupby("WaterYear").mean()
C:\Dino\COEQWAL\COEQWAL_GIT\COEQWAL_V3\notebooks\coeqwalpackage\metrics.py:1006: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  ann_mean = subset_df.groupby("WaterYear").mean()
C:\Dino\COEQWAL\COEQWAL_GIT\COEQWAL_V3\notebooks\coeqwalpackage\metrics.py:1006: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  ann_mean = subset_df.groupby("WaterYear").mean()
C:\Dino\COEQWAL\COEQWAL_GIT\COEQWAL_V3\notebooks\coeqwalpackage\metrics.py:1006: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  ann_mean = subset_df.groupby("WaterYear").mean()

A                CALSIM                                            \
B         S_SHSTA_s0001 S_SHSTA_s0002 S_SHSTA_s0003 S_SHSTA_s0004
C               STORAGE       STORAGE       STORAGE       STORAGE
D                  1MON          1MON          1MON          1MON
E                L2020A        L2020A        L2020A        L2020A
F              PER-AVER      PER-AVER      PER-AVER      PER-AVER
Units               TAF           TAF           TAF           TAF
WaterYear
1922          4552.1000     4552.1000     4552.1000     4552.1000
1923          4263.1230     4239.9090     4171.1353     4010.7420
1924          2834.6250     2546.8657     2359.4510     2438.9860
1925          3846.4575     3557.0237     3232.7852     3108.3752
1926          3872.9970     3687.7880     3290.8270     2963.1448

A                                                                  \
B         S_SHSTA_s0005 S_SHSTA_s0006 S_SHSTA_s0007 S_SHSTA_s0008
C               STORAGE       STORAGE       STORAGE       STORAGE
D                  1MON          1MON          1MON          1MON
E                L2020A        L2020A        L2020A        L2020A
F              PER-AVER      PER-AVER      PER-AVER      PER-AVER
Units               TAF           TAF           TAF           TAF
WaterYear
1922          4552.1000     4366.9140     4366.9140     4366.9140
1923          3992.2300     4097.5460     4074.9663     4068.6558
1924          2439.0420     2785.0469     2761.5180     2755.7869
1925          2945.7876     3908.2537     3887.1030     3880.6790
1926          2621.2085     4112.0140     4029.1260     4028.1350

A                                      ...                              \
B         S_SHSTA_s0009 S_SHSTA_s0010  ... S_MELON_s0042 S_MELON_s0044
C               STORAGE       STORAGE  ...       STORAGE       STORAGE
D                  1MON          1MON  ...          1MON          1MON
E                L2020A        L2020A  ...        L2020A        L2020A
F              PER-AVER      PER-AVER  ...      PER-AVER      PER-AVER
Units               TAF           TAF  ...           TAF           TAF
WaterYear                              ...
1922          4366.9140     4366.9140  ...     1616.0999     1664.6013
1923          4068.6145     4067.6423  ...     1855.5743     2028.7041
1924          2751.9968     2739.6897  ...     1760.9857     1834.6132
1925          3876.3730     3862.2240  ...     1640.2468     1858.9928
1926          4010.6917     3999.5007  ...     1672.4033     1828.6499

A                                                                  \
B         S_MELON_s0045 S_MELON_s0046 S_MELON_s0047 S_MELON_s0051
C               STORAGE       STORAGE       STORAGE       STORAGE
D                  1MON          1MON          1MON          1MON
E                L2020A        L2020A        L2020A        L2020A
F              PER-AVER      PER-AVER      PER-AVER      PER-AVER
Units               TAF           TAF           TAF           TAF
WaterYear
1922          1664.6013     1459.0868     1727.1992     1742.2806
1923          2028.7041     1563.0497     2120.1830     2166.4020
1924          1834.6132     1279.2343     1772.7507     1919.6638
1925          1858.9928     1062.6874     1906.6106     1849.1963
1926          1828.6499      843.5307     1819.5507     1786.0883

A
B         S_MELON_s0056 S_MELON_s0062 S_MELON_s0063 S_MELON_s0065
C               STORAGE       STORAGE       STORAGE       STORAGE
D                  1MON          1MON          1MON          1MON
E                L2020A        L2020A        L2020A        L2020A
F              PER-AVER      PER-AVER      PER-AVER      PER-AVER
Units               TAF           TAF           TAF           TAF
WaterYear
1922          1680.9974     1727.1992     1680.9974     1661.1472
1923          1994.6620     2120.1830     1994.6620     2029.7928
1924          1579.7366     1772.7507     1579.7366     1844.4229
1925          1662.2832     1906.6106     1662.2832     1869.1582
1926          1491.9408     1819.5507     1491.9408     1853.5537

[5 rows x 360 columns]

In [13]:
Apr_Storage_CV_df = compute_cv_scenario_variable(Apr_Storage_df)
Apr_Storage_CV_df.head(5)

Variable,S_FOLSM,S_MELON,S_MLRTN,S_OROVL,S_SHSTA,S_SLUIS_CVP,S_SLUIS_SWP,S_TRNTY
Scenario,,,,,,,,
s0001,0.179558,0.228007,0.310850,0.212192,0.164362,0.278326,0.376141,0.215741
s0002,0.198544,0.252658,0.296839,0.230273,0.196397,0.316346,0.354917,0.239156
s0003,0.257935,0.288925,0.249659,0.289735,0.241658,0.395529,0.396077,0.275506
s0004,0.287553,0.321842,0.251359,0.326807,0.267786,0.430809,0.414987,0.298745
s0005,0.297249,0.347511,0.261610,0.348947,0.281576,0.457439,0.424623,0.307092

In [14]:
Sep_Storage_df = compute_annual_means_list(storage_df, variables_storage, units=units, months=[9])
Sep_Storage_df.head(5)

C:\Dino\COEQWAL\COEQWAL_GIT\COEQWAL_V3\notebooks\coeqwalpackage\metrics.py:1006: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  ann_mean = subset_df.groupby("WaterYear").mean()
C:\Dino\COEQWAL\COEQWAL_GIT\COEQWAL_V3\notebooks\coeqwalpackage\metrics.py:1006: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  ann_mean = subset_df.groupby("WaterYear").mean()
C:\Dino\COEQWAL\COEQWAL_GIT\COEQWAL_V3\notebooks\coeqwalpackage\metrics.py:1006: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  ann_mean = subset_df.groupby("WaterYear").mean()
C:\Dino\COEQWAL\COEQWAL_GIT\COEQWAL_V3\notebooks\coeqwalpackage\metrics.py:1006: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  ann_mean = subset_df.groupby("WaterYear").mean()
C:\Dino\COEQWAL\COEQWAL_GIT\COEQWAL_V3\notebooks\coeqwalpackage\metrics.py:1006: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  ann_mean = subset_df.groupby("WaterYear").mean()
C:\Dino\COEQWAL\COEQWAL_GIT\COEQWAL_V3\notebooks\coeqwalpackage\metrics.py:1006: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  ann_mean = subset_df.groupby("WaterYear").mean()
C:\Dino\COEQWAL\COEQWAL_GIT\COEQWAL_V3\notebooks\coeqwalpackage\metrics.py:1006: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  ann_mean = subset_df.groupby("WaterYear").mean()
C:\Dino\COEQWAL\COEQWAL_GIT\COEQWAL_V3\notebooks\coeqwalpackage\metrics.py:1006: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  ann_mean = subset_df.groupby("WaterYear").mean()

A                CALSIM                                            \
B         S_SHSTA_s0001 S_SHSTA_s0002 S_SHSTA_s0003 S_SHSTA_s0004
C               STORAGE       STORAGE       STORAGE       STORAGE
D                  1MON          1MON          1MON          1MON
E                L2020A        L2020A        L2020A        L2020A
F              PER-AVER      PER-AVER      PER-AVER      PER-AVER
Units               TAF           TAF           TAF           TAF
WaterYear
1922          3399.9153    3376.82280     3020.8516     3073.8252
1923          3220.0823    3014.23020     2927.9705     2918.5564
1924          1226.1888     829.77466      550.0000      550.0000
1925          2787.5560    2752.85940     2299.2434     2121.0837
1926          2639.3853    2287.05700     1897.2922     1570.3761

A                                                                  \
B         S_SHSTA_s0005 S_SHSTA_s0006 S_SHSTA_s0007 S_SHSTA_s0008
C               STORAGE       STORAGE       STORAGE       STORAGE
D                  1MON          1MON          1MON          1MON
E                L2020A        L2020A        L2020A        L2020A
F              PER-AVER      PER-AVER      PER-AVER      PER-AVER
Units               TAF           TAF           TAF           TAF
WaterYear
1922          3186.2944     3400.0000     3400.0000     3400.0000
1923          2938.1794     3032.7610     3010.6968     3100.0889
1924           550.0000     1275.7760     1259.8429     1253.3451
1925          1930.2318     3094.5890     3111.0310     3110.3342
1926          1149.3823     2561.4998     2547.8848     2546.1170

A                                      ...                              \
B         S_SHSTA_s0009 S_SHSTA_s0010  ... S_MELON_s0042 S_MELON_s0044
C               STORAGE       STORAGE  ...       STORAGE       STORAGE
D                  1MON          1MON  ...          1MON          1MON
E                L2020A        L2020A  ...        L2020A        L2020A
F              PER-AVER      PER-AVER  ...      PER-AVER      PER-AVER
Units               TAF           TAF  ...           TAF           TAF
WaterYear                              ...
1922          3400.0000     3400.0000  ...     1576.7302     1775.9508
1923          3032.8640     2955.0242  ...     1740.3274     1861.4042
1924          1249.0951     1234.8113  ...     1430.9294     1452.2062
1925          3086.0720     3072.4958  ...     1536.8127     1697.5591
1926          2506.1190     2500.0000  ...     1313.8993     1431.1669

A                                                                  \
B         S_MELON_s0045 S_MELON_s0046 S_MELON_s0047 S_MELON_s0051
C               STORAGE       STORAGE       STORAGE       STORAGE
D                  1MON          1MON          1MON          1MON
E                L2020A        L2020A        L2020A        L2020A
F              PER-AVER      PER-AVER      PER-AVER      PER-AVER
Units               TAF           TAF           TAF           TAF
WaterYear
1922          1775.9508    1443.45670     1714.2803     1768.0153
1923          1861.4042    1322.61670     1818.9337     1951.8223
1924          1452.2062     860.75305     1400.1252     1359.8529
1925          1697.5591     797.99347     1686.7180     1666.9421
1926          1431.1669     378.89517     1370.0459     1374.6763

A
B         S_MELON_s0056 S_MELON_s0062 S_MELON_s0063 S_MELON_s0065
C               STORAGE       STORAGE       STORAGE       STORAGE
D                  1MON          1MON          1MON          1MON
E                L2020A        L2020A        L2020A        L2020A
F              PER-AVER      PER-AVER      PER-AVER      PER-AVER
Units               TAF           TAF           TAF           TAF
WaterYear
1922          1595.1158     1714.2804     1595.1158     1793.0540
1923          1646.0991     1818.9337     1646.0991     1880.9791
1924          1220.5454     1400.1252     1220.5454     1463.8390
1925          1400.9106     1686.7180     1400.9106     1726.0448
1926          1048.6145     1370.0459     1048.6145     1476.2976

[5 rows x 360 columns]

In [15]:
Sep_Storage_CV_df = compute_cv_scenario_variable(Sep_Storage_df)
Sep_Storage_CV_df.head(5)

Variable,S_FOLSM,S_MELON,S_MLRTN,S_OROVL,S_SHSTA,S_SLUIS_CVP,S_SLUIS_SWP,S_TRNTY
Scenario,,,,,,,,
s0001,0.258190,0.275559,0.281327,0.356666,0.239686,0.864778,0.621431,0.299024
s0002,0.313035,0.305549,0.279120,0.403519,0.289071,0.922751,0.640207,0.329655
s0003,0.405338,0.357833,0.197802,0.442940,0.371235,1.033085,0.603005,0.366579
s0004,0.425055,0.394182,0.181338,0.485067,0.406971,1.099368,0.635779,0.395690
s0005,0.433445,0.425432,0.172041,0.510607,0.421263,1.053311,0.589250,0.401068

In [16]:
Apr_Capacity_df = compute_annual_means_list(capacity_df, variables_capacity, units=units, months=[4])
Apr_Capacity_df = strip_leveldv_from_columns(Apr_Capacity_df, level_name="B")
Apr_Capacity_df = strip_level_from_columns(Apr_Capacity_df, level_name="B")
Apr_Capacity_df.head(5)

C:\Dino\COEQWAL\COEQWAL_GIT\COEQWAL_V3\notebooks\coeqwalpackage\metrics.py:1006: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  ann_mean = subset_df.groupby("WaterYear").mean()
C:\Dino\COEQWAL\COEQWAL_GIT\COEQWAL_V3\notebooks\coeqwalpackage\metrics.py:1006: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  ann_mean = subset_df.groupby("WaterYear").mean()
C:\Dino\COEQWAL\COEQWAL_GIT\COEQWAL_V3\notebooks\coeqwalpackage\metrics.py:1006: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  ann_mean = subset_df.groupby("WaterYear").mean()
C:\Dino\COEQWAL\COEQWAL_GIT\COEQWAL_V3\notebooks\coeqwalpackage\metrics.py:1006: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  ann_mean = subset_df.groupby("WaterYear").mean()
C:\Dino\COEQWAL\COEQWAL_GIT\COEQWAL_V3\notebooks\coeqwalpackage\metrics.py:1006: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  ann_mean = subset_df.groupby("WaterYear").mean()
C:\Dino\COEQWAL\COEQWAL_GIT\COEQWAL_V3\notebooks\coeqwalpackage\metrics.py:1006: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  ann_mean = subset_df.groupby("WaterYear").mean()
C:\Dino\COEQWAL\COEQWAL_GIT\COEQWAL_V3\notebooks\coeqwalpackage\metrics.py:1006: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  ann_mean = subset_df.groupby("WaterYear").mean()
C:\Dino\COEQWAL\COEQWAL_GIT\COEQWAL_V3\notebooks\coeqwalpackage\metrics.py:1006: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  ann_mean = subset_df.groupby("WaterYear").mean()

A                CALSIM                                            \
B         S_SHSTA_s0001 S_SHSTA_s0002 S_SHSTA_s0003 S_SHSTA_s0004
C         STORAGE-LEVEL STORAGE-LEVEL STORAGE-LEVEL STORAGE-LEVEL
D                  1MON          1MON          1MON          1MON
E                L2020A        L2020A        L2020A        L2020A
F              PER-AVER      PER-AVER      PER-AVER      PER-AVER
Units               TAF           TAF           TAF           TAF
WaterYear
1922             4552.0        4552.0        4552.0        4552.0
1923             4552.0        4552.0        4552.0        4552.0
1924             4552.0        4552.0        4552.0        4552.0
1925             4552.0        4552.0        4552.0        4552.0
1926             4552.0        4552.0        4552.0        4552.0

A                                                                  \
B         S_SHSTA_s0005 S_SHSTA_s0006 S_SHSTA_s0007 S_SHSTA_s0008
C         STORAGE-LEVEL STORAGE-LEVEL STORAGE-LEVEL STORAGE-LEVEL
D                  1MON          1MON          1MON          1MON
E                L2020A        L2020A        L2020A        L2020A
F              PER-AVER      PER-AVER      PER-AVER      PER-AVER
Units               TAF           TAF           TAF           TAF
WaterYear
1922             4552.0        4552.0        4552.0        4552.0
1923             4552.0        4552.0        4552.0        4552.0
1924             4552.0        4552.0        4552.0        4552.0
1925             4552.0        4552.0        4552.0        4552.0
1926             4552.0        4552.0        4552.0        4552.0

A                                      ...    MANUAL-ADD                \
B         S_SHSTA_s0009 S_SHSTA_s0010  ... S_MELON_s0042 S_MELON_s0044
C         STORAGE-LEVEL STORAGE-LEVEL  ...  STORAGE-ZONE  STORAGE-ZONE
D                  1MON          1MON  ...          1MON          1MON
E                L2020A        L2020A  ...        L2020A        L2020A
F              PER-AVER      PER-AVER  ...       PER-CUM       PER-CUM
Units               TAF           TAF  ...           TAF           TAF
WaterYear                              ...
1922             4552.0        4552.0  ...        2420.0        2420.0
1923             4552.0        4552.0  ...        2420.0        2420.0
1924             4552.0        4552.0  ...        2420.0        2420.0
1925             4552.0        4552.0  ...        2420.0        2420.0
1926             4552.0        4552.0  ...        2420.0        2420.0

A                                                                  \
B         S_MELON_s0045 S_MELON_s0046 S_MELON_s0047 S_MELON_s0051
C          STORAGE-ZONE  STORAGE-ZONE  STORAGE-ZONE  STORAGE-ZONE
D                  1MON          1MON          1MON          1MON
E                L2020A        L2020A        L2020A        L2020A
F               PER-CUM       PER-CUM       PER-CUM       PER-CUM
Units               TAF           TAF           TAF           TAF
WaterYear
1922             2420.0        2420.0        2420.0        2420.0
1923             2420.0        2420.0        2420.0        2420.0
1924             2420.0        2420.0        2420.0        2420.0
1925             2420.0        2420.0        2420.0        2420.0
1926             2420.0        2420.0        2420.0        2420.0

A
B         S_MELON_s0056 S_MELON_s0062 S_MELON_s0063 S_MELON_s0065
C          STORAGE-ZONE  STORAGE-ZONE  STORAGE-ZONE  STORAGE-ZONE
D                  1MON          1MON          1MON          1MON
E                L2020A        L2020A        L2020A        L2020A
F               PER-CUM       PER-CUM       PER-CUM       PER-CUM
Units               TAF           TAF           TAF           TAF
WaterYear
1922             2420.0        2420.0        2420.0        2420.0
1923             2420.0        2420.0        2420.0        2420.0
1924             2420.0        2420.0        2420.0        2420.0
1925             2420.0        2420.0        2420.0        2420.0
1926             2420.0        2420.0        2420.0        2420.0

[5 rows x 360 columns]

In [17]:
Sep_Capacity_df = compute_annual_means_list(capacity_df, variables_capacity, units=units, months=[9])
Sep_Capacity_df = strip_leveldv_from_columns(Sep_Capacity_df, level_name="B")
Sep_Capacity_df = strip_level_from_columns(Sep_Capacity_df, level_name="B")
Sep_Capacity_df.head(5)

C:\Dino\COEQWAL\COEQWAL_GIT\COEQWAL_V3\notebooks\coeqwalpackage\metrics.py:1006: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  ann_mean = subset_df.groupby("WaterYear").mean()
C:\Dino\COEQWAL\COEQWAL_GIT\COEQWAL_V3\notebooks\coeqwalpackage\metrics.py:1006: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  ann_mean = subset_df.groupby("WaterYear").mean()
C:\Dino\COEQWAL\COEQWAL_GIT\COEQWAL_V3\notebooks\coeqwalpackage\metrics.py:1006: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  ann_mean = subset_df.groupby("WaterYear").mean()
C:\Dino\COEQWAL\COEQWAL_GIT\COEQWAL_V3\notebooks\coeqwalpackage\metrics.py:1006: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  ann_mean = subset_df.groupby("WaterYear").mean()
C:\Dino\COEQWAL\COEQWAL_GIT\COEQWAL_V3\notebooks\coeqwalpackage\metrics.py:1006: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  ann_mean = subset_df.groupby("WaterYear").mean()
C:\Dino\COEQWAL\COEQWAL_GIT\COEQWAL_V3\notebooks\coeqwalpackage\metrics.py:1006: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  ann_mean = subset_df.groupby("WaterYear").mean()
C:\Dino\COEQWAL\COEQWAL_GIT\COEQWAL_V3\notebooks\coeqwalpackage\metrics.py:1006: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  ann_mean = subset_df.groupby("WaterYear").mean()
C:\Dino\COEQWAL\COEQWAL_GIT\COEQWAL_V3\notebooks\coeqwalpackage\metrics.py:1006: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  ann_mean = subset_df.groupby("WaterYear").mean()

A                CALSIM                                            \
B         S_SHSTA_s0001 S_SHSTA_s0002 S_SHSTA_s0003 S_SHSTA_s0004
C         STORAGE-LEVEL STORAGE-LEVEL STORAGE-LEVEL STORAGE-LEVEL
D                  1MON          1MON          1MON          1MON
E                L2020A        L2020A        L2020A        L2020A
F              PER-AVER      PER-AVER      PER-AVER      PER-AVER
Units               TAF           TAF           TAF           TAF
WaterYear
1922             4552.0        4552.0        4552.0        4552.0
1923             4552.0        4552.0        4552.0        4552.0
1924             4552.0        4552.0        4552.0        4552.0
1925             4552.0        4552.0        4552.0        4552.0
1926             4552.0        4552.0        4552.0        4552.0

A                                                                  \
B         S_SHSTA_s0005 S_SHSTA_s0006 S_SHSTA_s0007 S_SHSTA_s0008
C         STORAGE-LEVEL STORAGE-LEVEL STORAGE-LEVEL STORAGE-LEVEL
D                  1MON          1MON          1MON          1MON
E                L2020A        L2020A        L2020A        L2020A
F              PER-AVER      PER-AVER      PER-AVER      PER-AVER
Units               TAF           TAF           TAF           TAF
WaterYear
1922             4552.0        4552.0        4552.0        4552.0
1923             4552.0        4552.0        4552.0        4552.0
1924             4552.0        4552.0        4552.0        4552.0
1925             4552.0        4552.0        4552.0        4552.0
1926             4552.0        4552.0        4552.0        4552.0

A                                      ...    MANUAL-ADD                \
B         S_SHSTA_s0009 S_SHSTA_s0010  ... S_MELON_s0042 S_MELON_s0044
C         STORAGE-LEVEL STORAGE-LEVEL  ...  STORAGE-ZONE  STORAGE-ZONE
D                  1MON          1MON  ...          1MON          1MON
E                L2020A        L2020A  ...        L2020A        L2020A
F              PER-AVER      PER-AVER  ...       PER-CUM       PER-CUM
Units               TAF           TAF  ...           TAF           TAF
WaterYear                              ...
1922             4552.0        4552.0  ...        2420.0        2420.0
1923             4552.0        4552.0  ...        2420.0        2420.0
1924             4552.0        4552.0  ...        2420.0        2420.0
1925             4552.0        4552.0  ...        2420.0        2420.0
1926             4552.0        4552.0  ...        2420.0        2420.0

A                                                                  \
B         S_MELON_s0045 S_MELON_s0046 S_MELON_s0047 S_MELON_s0051
C          STORAGE-ZONE  STORAGE-ZONE  STORAGE-ZONE  STORAGE-ZONE
D                  1MON          1MON          1MON          1MON
E                L2020A        L2020A        L2020A        L2020A
F               PER-CUM       PER-CUM       PER-CUM       PER-CUM
Units               TAF           TAF           TAF           TAF
WaterYear
1922             2420.0        2420.0        2420.0        2420.0
1923             2420.0        2420.0        2420.0        2420.0
1924             2420.0        2420.0        2420.0        2420.0
1925             2420.0        2420.0        2420.0        2420.0
1926             2420.0        2420.0        2420.0        2420.0

A
B         S_MELON_s0056 S_MELON_s0062 S_MELON_s0063 S_MELON_s0065
C          STORAGE-ZONE  STORAGE-ZONE  STORAGE-ZONE  STORAGE-ZONE
D                  1MON          1MON          1MON          1MON
E                L2020A        L2020A        L2020A        L2020A
F               PER-CUM       PER-CUM       PER-CUM       PER-CUM
Units               TAF           TAF           TAF           TAF
WaterYear
1922             2420.0        2420.0        2420.0        2420.0
1923             2420.0        2420.0        2420.0        2420.0
1924             2420.0        2420.0        2420.0        2420.0
1925             2420.0        2420.0        2420.0        2420.0
1926             2420.0        2420.0        2420.0        2420.0

[5 rows x 360 columns]

In [18]:
Apr_StoPct_df = compute_percent_of_capacity(Apr_Storage_df, Apr_Capacity_df)
Apr_StoPct_df.head(5)

A                CALSIM                                            \
B         S_FOLSM_s0001 S_FOLSM_s0002 S_FOLSM_s0003 S_FOLSM_s0004
C               STORAGE       STORAGE       STORAGE       STORAGE
D                  1MON          1MON          1MON          1MON
E                L2020A        L2020A        L2020A        L2020A
F               PERCENT       PERCENT       PERCENT       PERCENT
Units               TAF           TAF           TAF           TAF
WaterYear
1922          93.071355     93.071355     93.071355     93.071355
1923          93.071355     93.071355     93.071355     93.071525
1924          41.554984     41.644391     32.770757     37.074323
1925          93.071355     93.071355     93.071355     80.918649
1926          90.052534     86.170917     77.502172     80.917177

A                                                                  \
B         S_FOLSM_s0005 S_FOLSM_s0006 S_FOLSM_s0007 S_FOLSM_s0008
C               STORAGE       STORAGE       STORAGE       STORAGE
D                  1MON          1MON          1MON          1MON
E                L2020A        L2020A        L2020A        L2020A
F               PERCENT       PERCENT       PERCENT       PERCENT
Units               TAF           TAF           TAF           TAF
WaterYear
1922          93.071355     93.071355     93.071355     93.071355
1923          93.071835     93.071355     93.071355     93.071355
1924          33.993912     38.711359     41.444503     40.913024
1925          74.192658     93.071355     93.071355     93.071355
1926          81.006996     87.496019     89.987952     90.058339

A                                      ...                              \
B         S_FOLSM_s0009 S_FOLSM_s0010  ... S_TRNTY_s0042 S_TRNTY_s0044
C               STORAGE       STORAGE  ...       STORAGE       STORAGE
D                  1MON          1MON  ...          1MON          1MON
E                L2020A        L2020A  ...        L2020A        L2020A
F               PERCENT       PERCENT  ...       PERCENT       PERCENT
Units               TAF           TAF  ...           TAF           TAF
WaterYear                              ...
1922          93.071355     93.071355  ...     77.406418     77.565265
1923          93.071355     93.071355  ...     79.831406     72.820857
1924          40.306982     44.510645  ...     54.640292     46.556358
1925          93.071355     93.071355  ...     66.398260     67.309366
1926          87.162343     86.590936  ...     76.034703     72.898302

A                                                                  \
B         S_TRNTY_s0045 S_TRNTY_s0046 S_TRNTY_s0047 S_TRNTY_s0051
C               STORAGE       STORAGE       STORAGE       STORAGE
D                  1MON          1MON          1MON          1MON
E                L2020A        L2020A        L2020A        L2020A
F               PERCENT       PERCENT       PERCENT       PERCENT
Units               TAF           TAF           TAF           TAF
WaterYear
1922          77.522914     64.576823     83.880898     83.500517
1923          72.921664     49.119678     70.044676     68.257651
1924          42.573456     33.532999     35.291474     40.302556
1925          59.378130     43.385182     63.052765     70.144575
1926          65.588462     41.678265     62.434641     64.864646

A
B         S_TRNTY_s0056 S_TRNTY_s0062 S_TRNTY_s0063 S_TRNTY_s0065
C               STORAGE       STORAGE       STORAGE       STORAGE
D                  1MON          1MON          1MON          1MON
E                L2020A        L2020A        L2020A        L2020A
F               PERCENT       PERCENT       PERCENT       PERCENT
Units               TAF           TAF           TAF           TAF
WaterYear
1922          82.574016     83.862448     82.558352     76.110996
1923          59.502662     69.862031     59.576974     73.876245
1924          31.217278     35.046432     31.393986     47.004408
1925          61.944575     66.525202     62.116949     67.374024
1926          54.668776     65.765036     59.665295     73.010010

[5 rows x 360 columns]

In [19]:
Sep_StoPct_df = compute_percent_of_capacity(Sep_Storage_df, Sep_Capacity_df)
Sep_StoPct_df.head(5)

A                CALSIM                                            \
B         S_FOLSM_s0001 S_FOLSM_s0002 S_FOLSM_s0003 S_FOLSM_s0004
C               STORAGE       STORAGE       STORAGE       STORAGE
D                  1MON          1MON          1MON          1MON
E                L2020A        L2020A        L2020A        L2020A
F               PERCENT       PERCENT       PERCENT       PERCENT
Units               TAF           TAF           TAF           TAF
WaterYear
1922          73.778459     73.965253     73.911799     73.903092
1923          62.186381     63.242740     58.291324     65.972982
1924          28.112947     26.763553      9.307135      9.307135
1925          66.829835     67.708873     60.331954     60.663915
1926          47.422754     44.686719     48.056737     48.830832

A                                                                  \
B         S_FOLSM_s0005 S_FOLSM_s0006 S_FOLSM_s0007 S_FOLSM_s0008
C               STORAGE       STORAGE       STORAGE       STORAGE
D                  1MON          1MON          1MON          1MON
E                L2020A        L2020A        L2020A        L2020A
F               PERCENT       PERCENT       PERCENT       PERCENT
Units               TAF           TAF           TAF           TAF
WaterYear
1922          73.780465     77.598046     73.244264     77.596629
1923          64.428718     61.283526     67.744340     67.744436
1924           9.307135     28.831768     31.225024     30.950915
1925          61.122341     57.003213     59.528325     59.745806
1926          45.233340     41.952195     41.639690     41.609506

A                                      ...                              \
B         S_FOLSM_s0009 S_FOLSM_s0010  ... S_TRNTY_s0042 S_TRNTY_s0044
C               STORAGE       STORAGE  ...       STORAGE       STORAGE
D                  1MON          1MON  ...          1MON          1MON
E                L2020A        L2020A  ...        L2020A        L2020A
F               PERCENT       PERCENT  ...       PERCENT       PERCENT
Units               TAF           TAF  ...           TAF           TAF
WaterYear                              ...
1922          77.512995     71.261489  ...     77.927036     66.155962
1923          67.743888     67.743837  ...     62.856160     51.376806
1924          30.367580     34.084512  ...     28.924348     29.947182
1925          56.665491     56.086077  ...     61.186624     58.760562
1926          40.814058     40.136460  ...     46.357343     44.365698

A                                                                  \
B         S_TRNTY_s0045 S_TRNTY_s0046 S_TRNTY_s0047 S_TRNTY_s0051
C               STORAGE       STORAGE       STORAGE       STORAGE
D                  1MON          1MON          1MON          1MON
E                L2020A        L2020A        L2020A        L2020A
F               PERCENT       PERCENT       PERCENT       PERCENT
Units               TAF           TAF           TAF           TAF
WaterYear
1922          65.735820     48.589198     61.542373     58.250007
1923          51.326117     40.251580     40.033783     45.981439
1924          21.611133     20.930059     18.262949     25.468989
1925          50.723482     37.086673     47.459285     50.956959
1926          39.969199     26.286606     37.092932     37.873462

A
B         S_TRNTY_s0056 S_TRNTY_s0062 S_TRNTY_s0063 S_TRNTY_s0065
C               STORAGE       STORAGE       STORAGE       STORAGE
D                  1MON          1MON          1MON          1MON
E                L2020A        L2020A        L2020A        L2020A
F               PERCENT       PERCENT       PERCENT       PERCENT
Units               TAF           TAF           TAF           TAF
WaterYear
1922          50.962184     61.331073     50.973362     68.284432
1923          36.412602     39.757094     36.604980     52.349670
1924          18.963512     21.751995     19.136769     30.101423
1925          41.361449     51.385349     45.776381     59.151300
1926          31.304089     43.074324     37.176600     45.693024

[5 rows x 360 columns]

In [20]:
Apr_StoPct_CV_df = compute_cv_scenario_variable(Apr_StoPct_df)
Apr_StoPct_CV_df.head(5)

Variable,S_FOLSM,S_MELON,S_MLRTN,S_OROVL,S_SHSTA,S_SLUIS_CVP,S_SLUIS_SWP,S_TRNTY
Scenario,,,,,,,,
s0001,0.179558,0.228007,0.310850,0.212192,0.164362,0.278326,0.376141,0.215741
s0002,0.198544,0.252658,0.296839,0.230273,0.196397,0.316346,0.354917,0.239156
s0003,0.257935,0.288925,0.249659,0.289735,0.241658,0.395529,0.396077,0.275506
s0004,0.287553,0.321842,0.251359,0.326807,0.267786,0.430809,0.414987,0.298745
s0005,0.297249,0.347511,0.261610,0.348947,0.281576,0.457439,0.424623,0.307092

In [21]:
Sep_StoPct_CV_df = compute_cv_scenario_variable(Sep_StoPct_df)
Sep_StoPct_CV_df.head(5)

Variable,S_FOLSM,S_MELON,S_MLRTN,S_OROVL,S_SHSTA,S_SLUIS_CVP,S_SLUIS_SWP,S_TRNTY
Scenario,,,,,,,,
s0001,0.258190,0.275559,0.281327,0.356666,0.239686,0.864778,0.621431,0.299024
s0002,0.313035,0.305549,0.279120,0.403519,0.289071,0.922751,0.640207,0.329655
s0003,0.405338,0.357833,0.197802,0.442940,0.371235,1.033085,0.603005,0.366579
s0004,0.425055,0.394182,0.181338,0.485067,0.406971,1.099368,0.635779,0.395690
s0005,0.433445,0.425432,0.172041,0.510607,0.421263,1.053311,0.589250,0.401068

In [22]:
flood_clean_df = strip_leveldv_from_columns(flood_df, level_name="B")
flood_clean_df = strip_level_from_columns(flood_clean_df, level_name="B")

In [23]:
SpillFreq_df, SpillProb_df = freq_and_prob_storage_ge_flood(storage_df, flood_clean_df)
SpillFreq_df.head(10)

variable,S_FOLSM,S_MELON,S_MLRTN,S_OROVL,S_SHSTA,S_SLUIS_CVP,S_SLUIS_SWP,S_TRNTY
scenario,,,,,,,,
s0001,518,179,62,258,400,94,79,219
s0002,508,196,60,252,378,92,88,209
s0003,407,145,79,199,267,66,72,133
s0004,366,133,76,173,231,56,62,111
s0005,336,120,79,160,211,50,51,97
s0006,<NA>,197,143,244,364,102,69,208
s0007,<NA>,197,143,242,362,105,192,215
s0008,<NA>,197,143,240,361,106,216,217
s0009,<NA>,197,143,242,361,109,227,218
s0010,<NA>,197,143,242,362,110,228,217

In [24]:
SpillProb_df.head(10)

variable,S_FOLSM,S_MELON,S_MLRTN,S_OROVL,S_SHSTA,S_SLUIS_CVP,S_SLUIS_SWP,S_TRNTY
scenario,,,,,,,,
s0001,0.431667,0.149167,0.051667,0.215000,0.333333,0.078333,0.065833,0.182500
s0002,0.423333,0.163333,0.050000,0.210000,0.315000,0.076667,0.073333,0.174167
s0003,0.339167,0.120833,0.065833,0.165833,0.222500,0.055000,0.060000,0.110833
s0004,0.305000,0.110833,0.063333,0.144167,0.192500,0.046667,0.051667,0.092500
s0005,0.280000,0.100000,0.065833,0.133333,0.175833,0.041667,0.042500,0.080833
s0006,NaN,0.164167,0.119167,0.203333,0.303333,0.085000,0.057500,0.173333
s0007,NaN,0.164167,0.119167,0.201667,0.301667,0.087500,0.160000,0.179167
s0008,NaN,0.164167,0.119167,0.200000,0.300833,0.088333,0.180000,0.180833
s0009,NaN,0.164167,0.119167,0.201667,0.300833,0.090833,0.189167,0.181667
s0010,NaN,0.164167,0.119167,0.201667,0.301667,0.091667,0.190000,0.180833

## Save outputs

In [25]:
Apr_Storage_df.to_csv(Apr_Storage_Volume_path)
Sep_Storage_df.to_csv(Sep_Storage_Volume_path)
Apr_Storage_CV_df.to_csv(Apr_Storage_Volume_CV_path)
Sep_Storage_CV_df.to_csv(Sep_Storage_Volume_CV_path)
Apr_StoPct_df.to_csv(Apr_Storage_Percent_path)
Sep_StoPct_df.to_csv(Sep_Storage_Percent_path)
Apr_StoPct_CV_df.to_csv(Apr_Storage_Percent_CV_path)
Sep_StoPct_CV_df.to_csv(Sep_Storage_Percent_CV_path)
SpillFreq_df.to_csv(Spill_Frequency_path)
SpillProb_df.to_csv(Spill_Probability_path)

## Merge All Metrics

In [26]:
# Combine tiers and probabilities into single DataFrame
# Note: tier_df columns already have _Storage_Tier suffix, no need to add more
prob_renamed = prob_df.add_suffix('_LevelProb')
SpillFreq_renamed = SpillFreq_df.add_suffix('_SpillFreq')
SpillProb_renamed = SpillProb_df.add_suffix('_SpillProb')

df_combined = pd.concat([
    tier_df,  # already has _Storage_Tier suffix
    prob_renamed,
    SpillFreq_renamed,
    SpillProb_renamed
], axis=1)

# Save combined output
combined_output_path = os.path.join(data_output_dir, all_metrics_filename)
df_combined.to_csv(combined_output_path)
print(f"Combined metrics saved to: {combined_output_path}")
print(f"Shape: {df_combined.shape[0]} scenarios x {df_combined.shape[1]} columns")
display(df_combined.head())

Combined metrics saved to: C:\Dino\COEQWAL\COEQWAL_GIT\CalSim3_Model_Runs\Scenarios\Performance_Metrics\Metrics\Reservoir_Storage\storage_all_metrics.csv
Shape: 45 scenarios x 56 columns

,S_SHSTA_Storage_Tier,S_TRNTY_Storage_Tier,S_OROVL_Storage_Tier,S_FOLSM_Storage_Tier,S_MELON_Storage_Tier,S_MLRTN_Storage_Tier,S_SLUIS_CVP_Storage_Tier,S_SLUIS_SWP_Storage_Tier,S_SHSTA_Storage_TopProb_LevelProb,S_SHSTA_Storage_MidProb_LevelProb,...,S_SLUIS_SWP_SpillFreq,S_TRNTY_SpillFreq,S_FOLSM_SpillProb,S_MELON_SpillProb,S_MLRTN_SpillProb,S_OROVL_SpillProb,S_SHSTA_SpillProb,S_SLUIS_CVP_SpillProb,S_SLUIS_SWP_SpillProb,S_TRNTY_SpillProb
s0001,2.0,3.0,2.0,3.0,2.0,3.0,3.0,3.0,0.55,0.25,...,79,219,0.431667,0.149167,0.051667,0.215000,0.333333,0.078333,0.065833,0.182500
s0002,2.0,3.0,3.0,3.0,2.0,3.0,3.0,3.0,0.50,0.23,...,88,209,0.423333,0.163333,0.050000,0.210000,0.315000,0.076667,0.073333,0.174167
s0003,3.0,3.0,3.0,3.0,2.0,2.0,3.0,3.0,0.39,0.25,...,72,133,0.339167,0.120833,0.065833,0.165833,0.222500,0.055000,0.060000,0.110833
s0004,3.0,3.0,3.0,3.0,2.0,2.0,3.0,3.0,0.34,0.23,...,62,111,0.305000,0.110833,0.063333,0.144167,0.192500,0.046667,0.051667,0.092500
s0005,3.0,3.0,3.0,3.0,2.0,3.0,3.0,3.0,0.31,0.21,...,51,97,0.280000,0.100000,0.065833,0.133333,0.175833,0.041667,0.042500,0.080833

In [27]:
print("Done!")

Done!